# Pandas tutorial for Asia University

In [0]:
import pandas as pd
import numpy as np

In [0]:
dat = pd.read_csv('Pokemon_g1.csv', encoding = 'Windows-1252')

In [0]:
dat.head()

   #                   Name Type 1  Type 2  ...  Defense  Sp. Atk  Sp. Def  Speed
0  1              Bulbasaur  Grass  Poison  ...       49       65       65     45
1  2                Ivysaur  Grass  Poison  ...       63       80       80     60
2  3               Venusaur  Grass  Poison  ...       83      100      100     80
3  3  VenusaurMega Venusaur  Grass  Poison  ...      123      122      120     80
4  4             Charmander   Fire     NaN  ...       43       60       50     65

[5 rows x 11 columns]

# Groupby

- [官方文件](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html)

In [0]:
#dat.groupby('Type 1', as_index=False).agg({"Attack":"mean"})
dat.groupby('Type 1', as_index=False).Attack.mean()

      Type 1      Attack
0        Bug   76.428571
1     Dragon   94.000000
2   Electric   62.000000
3      Fairy   57.500000
4   Fighting  102.857143
5       Fire   88.642857
6      Ghost   53.750000
7      Grass   72.923077
8     Ground   81.875000
9        Ice   67.500000
10    Normal   70.625000
11    Poison   75.769231
12   Psychic   79.181818
13      Rock   87.500000
14     Water   74.193548

### 動手試試看
- 請計算各個屬性(Type 1)在能力總和(Total)上的平均值，以及速度(Speed)的最小值，並依照能力總和平均由大排到小

---

# Merge, Join, and Concatenate

[Merge, join, and concatenate](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html)

In [0]:
dat_extra = pd.read_csv('Pokemon_g1_extra.csv', encoding = 'Windows-1252')

In [0]:
dat_extra.head()

   #                   Name Generation Legendary
0  1              Bulbasaur          1     False
1  2                Ivysaur          1     False
2  3               Venusaur          1     False
3  3  VenusaurMega Venusaur          1     False
4  4             Charmander          1     False

In [0]:
# 根據index 來增加欄位

dat.join(dat_extra[['Generation', 'Legendary']]).head()

   #                   Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
0  1              Bulbasaur  Grass  Poison  ...       65     45           1      False
1  2                Ivysaur  Grass  Poison  ...       80     60           1      False
2  3               Venusaur  Grass  Poison  ...      100     80           1      False
3  3  VenusaurMega Venusaur  Grass  Poison  ...      120     80           1      False
4  4             Charmander   Fire     NaN  ...       50     65           1      False

[5 rows x 13 columns]

In [0]:
# 根據兩份資料的特定欄位數值來合併資料，與SQL join 類似

merge_dat = pd.merge(dat, dat_extra, on = 'Name')

merge_dat.head()

   #_x                   Name Type 1  Type 2  ...  Speed  #_y  Generation  Legendary
0    1              Bulbasaur  Grass  Poison  ...     45    1           1      False
1    2                Ivysaur  Grass  Poison  ...     60    2           1      False
2    3               Venusaur  Grass  Poison  ...     80    3           1      False
3    3  VenusaurMega Venusaur  Grass  Poison  ...     80    3           1      False
4    4             Charmander   Fire     NaN  ...     65    4           1      False

[5 rows x 14 columns]

In [0]:
# concat 可以指定增加欄位或是資料筆數，但會直接以原本的排序下去合併，不會做欄位的對應
concate_data = [dat[0:5], dat[10:15]]

pd.concat( concate_data, axis = 0)

     #                     Name Type 1  ... Sp. Atk  Sp. Def  Speed
0    1                Bulbasaur  Grass  ...      65       65     45
1    2                  Ivysaur  Grass  ...      80       80     60
2    3                 Venusaur  Grass  ...     100      100     80
3    3    VenusaurMega Venusaur  Grass  ...     122      120     80
4    4               Charmander   Fire  ...      60       50     65
10   8                Wartortle  Water  ...      65       80     58
11   9                Blastoise  Water  ...      85      105     78
12   9  BlastoiseMega Blastoise  Water  ...     135      115     78
13  10                 Caterpie    Bug  ...      20       20     45
14  11                  Metapod    Bug  ...      25       25     30

[10 rows x 11 columns]

In [0]:
# concat 可以指定增加欄位或是資料筆數，但會直接以原本的排序下去合併，不會做欄位的對應
concate_data = [dat['Name'], dat['Speed']]

pd.concat(concate_data, axis = 1).head()

                    Name  Speed
0              Bulbasaur     45
1                Ivysaur     60
2               Venusaur     80
3  VenusaurMega Venusaur     80
4             Charmander     65

### 動手試試看

- 下方已經準備好兩份資料(分別記錄了班上同學的作業分數與期中考分數)，請將此兩份資料合併起來

In [0]:
class_dat_1 = pd.DataFrame({'ID':['B0971204','B0981142','B0972830','B0996029'],
                            'homework':[90, 85, 76, 88]})
class_dat_2 = pd.DataFrame({'ID':['B0996029','B0972830','B0981142','B1003852'],
                            'midterm':[63, 80, 93, 85]})

In [0]:
#merge_dat = pd.merge(class_dat_1, class_dat_2, on = 'ID')
#merge_dat.head()

class_dat_1.join(class_dat_2[['ID', 'midterm']]) #??

ValueError: ignored

---

# Apply

In [0]:
dat.loc[:,'Total':'Speed'].apply(np.mean, axis = 0)

Total      425.445783
HP          65.885542
Attack      76.536145
Defense     70.861446
Sp. Atk     71.819277
Sp. Def     69.150602
Speed       72.289157
dtype: float64

In [0]:
def grade(row):
    if (row['Attack']>100)|(row['Sp. Atk']>100):
        return 'awesome'
    elif (row['Attack']>80)&(row['Speed']>80):
        return 'awesome'
    elif (row['Defense']>60)|(row['HP']>60):
        return 'good'
    else:
        return 'soso'

dat_2 = dat.copy()

dat_2['grade'] = dat_2.apply(grade, axis = 1)

dat_2.head()

   #                   Name Type 1  Type 2  ...  Sp. Atk  Sp. Def  Speed    grade
0  1              Bulbasaur  Grass  Poison  ...       65       65     45     soso
1  2                Ivysaur  Grass  Poison  ...       80       80     60     good
2  3               Venusaur  Grass  Poison  ...      100      100     80     good
3  3  VenusaurMega Venusaur  Grass  Poison  ...      122      120     80  awesome
4  4             Charmander   Fire     NaN  ...       60       50     65     soso

[5 rows x 12 columns]

### 動手試試看
請計算出各個屬性(Type 1)中有幾隻神奇寶貝速度(Speed)在60以下

---

# Cross_table, pivot_table, and melt

In [0]:
pd.crosstab(dat_2['Type 1'], dat_2['grade'])

In [0]:
dat_2.pivot_table(values='Total', index='Type 1', columns='grade', aggfunc=np.mean)

In [0]:
pivot_dat = dat_2.pivot_table(values='Total', index='Type 1', columns='grade', aggfunc=np.mean)
pivot_dat.reset_index(inplace = True)

pivot_dat.head()

In [0]:
pivot_dat.melt(id_vars=['Type 1'], value_vars=['awesome','good','soso']).head(20)

### 動手試試看
下方已幫各位合併了dat_2 與 dat_extra 兩資料，請以傳說與否(Legendary)為row、評分(grade)為column並計算Speed的最大值

In [0]:
def grade(row):
    if (row['Attack']>100)|(row['Sp. Atk']>100):
        return 'awesome'
    elif (row['Attack']>80)&(row['Speed']>80):
        return 'awesome'
    elif (row['Defense']>60)|(row['HP']>60):
        return 'good'
    else:
        return 'soso'

dat_2 = dat.copy()
dat_2['grade'] = dat_2.apply(grade, axis = 1)

dat_extra = pd.read_csv('Pokemon_g1_extra.csv', encoding = 'Windows-1252')

In [0]:
dat_merge = pd.merge(dat_2, dat_extra.drop('#', axis = 1), on = 'Name')
dat_merge.head()

---

# Plot

### histogram

In [0]:
dat['Attack'].hist()

### barplot

In [0]:
type_counts = dat['Type 1'].value_counts()

type_counts.plot.bar()

### scatter plot

In [0]:
dat.plot.scatter('Attack','Defense')

---

# 寫出檔案

In [0]:
dat.to_csv('out_data.csv', index = False)